server:
  servlet:
    context-path: /100
  port: 8000

---
spring:
  profiles:
    active: dev

---
spring:
  jpa:
    show-sql: false
    database-platform: io.fashionet.core.base.utils.database.Mysql57InnoDBDialectUtf8mb4
    hibernate:
      naming.implicit-strategy: io.fashionet.core.base.utils.database.SimpleImplicitNamingStrategyImpl

---
spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      enabled: true